// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOm5qnAKArSiTSXmj9wQDLX131e_59hZ4',
    appId: '1:217941143201:web:c9881cdb69dc57a4628ae0',
    messagingSenderId: '217941143201',
    projectId: 'webappvizola',
    authDomain: 'webappvizola.firebaseapp.com',
    storageBucket: 'webappvizola.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaR4JTDd-KZrALvFdlOZMHZz9qTQy3wBQ',
    appId: '1:217941143201:android:2b381a4c33f7ddb6628ae0',
    messagingSenderId: '217941143201',
    projectId: 'webappvizola',
    storageBucket: 'webappvizola.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTJ_Ul0sQSJdT_O9vJNg9uRRmeXSvr78s',
    appId: '1:217941143201:ios:aafe92b6d78a87c9628ae0',
    messagingSenderId: '217941143201',
    projectId: 'webappvizola',
    storageBucket: 'webappvizola.appspot.com',
    iosClientId: '217941143201-pd2uajcl0jrk35ufdbnlndirg9a15ahd.apps.googleusercontent.com',
    iosBundleId: 'com.example.webapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTJ_Ul0sQSJdT_O9vJNg9uRRmeXSvr78s',
    appId: '1:217941143201:ios:9b8a12789ccb587a628ae0',
    messagingSenderId: '217941143201',
    projectId: 'webappvizola',
    storageBucket: 'webappvizola.appspot.com',
    iosClientId: '217941143201-5ni67rog1omcsbafsq67t7ihe9ubjin4.apps.googleusercontent.com',
    iosBundleId: 'com.example.webapp.RunnerTests',
  );
}
